### ISSUE TITLE
Install git in your local

### ISSUE THREAD

**Issue by madnira** [GOL-org/temp#6]

**Comment by shryta234** [comment]
Shruti - Completed - Version - 2.14.1 - 64bit

**Comment by madnira** [comment]
I have done it. I have cloned the gol/temp repo on my local and pushed it in remote with a modified branch

**Comment by madnira** [comment]
@rathore-abhay  have installed and cloned

**Comment by madnira** [comment]
@shryta234 check whether you can clone the gol/temp in your local and we can close the story.
